### ISSUE TITLE
[request] Handling of tamed/owned creatures

### ISSUE THREAD

**Issue by Suitov** [Rongmario/CleanCut#1]
It'd be fantastic if mobs registered as owned by the player were excluded - an improvement I'm suggesting as a direct result of trying to harvest crops and accidentally punching my dogs. (Either I'm clumsy or they're suicidal...)

Optional/nice to have: toggle for inclusion of mobs registered as owned by **other** players, allowing better control depending if you're on a peaceful server with friends or are playing PVP.

**Comment by Rongmario** [comment]
I'll make tamed entities not able to be attacked via a config option. Thank you for the suggestion!

**Comment by Rongmario** [comment]
Fixed as of https://github.com/Rongmario/CleanCut/commit/96a0e4065b7c878068df3e9c7152a9ae7e26675f
