### ISSUE TITLE
Clean cut 1.18.2 does not hit the mob at the same time when hitting tall grass 

### ISSUE THREAD

**Issue by Celesian** [Rongmario/CleanCut#13]
Minecraft 1.18.2
Fabric api 0.48.0+1.18.2
Cleancut 1.18-4.0

1. put a mob into some tall grass
2. hit it with a sword

What happened: you hit the grass not the mob https://youtu.be/9gaXVhiSgCo
What I expected: you hit the mob and the grass at the same time (recorded in Minecraft. 1.18.1, Cleancut 1.18-4.0 and fabric api 0.46.6) https://youtu.be/sTIZzg8VXTE

**Comment by roberestarkk** [comment]
I'm having the same issue... 
Here's the logs from a session where I tried to hit a mob:
https://pastebin.com/9DiA0bfX

Here's a log with just clean cut and fabric installed, same issue:
https://pastebin.com/WbzL0D75

**Comment by Rongmario** [comment]
Fixed in latest.
