### ISSUE TITLE
Hitting entities through slime and honeyblocks and tnt.

### ISSUE THREAD

**Issue by Flyvee** [Rongmario/CleanCut#20]
Can there be made a config option so that players won't be able to hit entities through blocks with 0 hardness? Because being able to hit someone behind honey, slime or tnt seems a weird thing to be able to do.

**Comment by Rongmario** [comment]
Fixed as of https://github.com/Rongmario/CleanCut/commit/96a0e4065b7c878068df3e9c7152a9ae7e26675f
