### ISSUE TITLE
[Request] Modrinth listing?

### ISSUE THREAD

**Issue by sisby-folk** [Rongmario/CleanCut#26]
Hey there! We've only got a couple of curseforge-only mods left in our [small modpack](https://modrinth.com/modpack/tinkerers-quilt) and we'd prefer it to count as a proper download instead of just jamming in the jar! Would it be possible to post cleancut on modrinth?

Our pack is 1.19.2, so if you could post versions back at least that far that'd be super helpful!

**Comment by Rongmario** [comment]
I can't upload onto Modrinth I'm afraid, the admins blocked me for reasons I do not know.
