### ISSUE TITLE
Incompatible Datapack(s)

### ISSUE THREAD

**Issue by Coraline77447** [Rongmario/CleanCut#3]
Hi. I'm here to report an issue involving datapacks with this mod and why I'm reporting this about it's datapack(s) is cause I'm sick and tired of losing my worlds due to incomplete or missing data within the datapacks or outdated datapacks of some of the mods that I'm playing with which at some point I lose the world that I would be playing on and how I know this is cause when making a new world you can apply datapacks except for datapacks that mods adds and when I look in there I see some red ones that when I hover my mouse over them they say "Incompatible, made for an older version of Minecraft." When I would try to load into a modded world I get a message that says that the selected datapacks have errors and asks me to either enter safe mode (which I can't enter safe mode) or go to title screen and in the message it says that I can manually fix them which Idk how to fix incomplete, missing, outdated, or even broken datapacks to mods that has these errors!!!

**Comment by Rongmario** [comment]
Stop schizoposting, get some help, this mod touches nothing of datapacks.

**Comment by Coraline77447** [comment]
Then why did my game tell me that it has an incompatible datapack which caused me not to be able to rejoin my last modded world? I don't know why this is happening to this mod when its obvious that it doesn't touch datapacks at all but then why does the stupid game says otherwise? I'm just asking btw and sorry for making you frustrated about this...just wanted to use this mod to be able to hit my enemies through the damn grass without having an issue with the mod like this cause I wont play modded minecraft with any mod that has incompatible datapack(s) or else I lose my worlds due to this issue but if there's no fix for this for this mod then I guess I'll have to keep hitting the damn grass while in combat.....(I know that this issue is closed now but I just wanted to tell you what I've said in this reply...)

**Comment by Rongmario** [comment]
It's definitely not because of this mod.
