### ISSUE TITLE
1.20.1 😤

### ISSUE THREAD

**Issue by CormacZ** [Rongmario/CleanCut#30]

**Comment by CormacZ** [comment]
Also, is this you? [CleanCut](https://modrinth.com/mod/cleancut)

**Comment by Rongmario** [comment]
@Ametsuchiru will be handling most of the updating now. [I've given them and the organization to be able to redistribute my mods on modrinth.](https://github.com/Exoneration)

**Comment by CormacZ** [comment]
Oooh okay then
