### ISSUE TITLE
Hitting mobs through solid blocks

### ISSUE THREAD

**Issue by ohnecksThing** [Rongmario/CleanCut#8]
This mod is good, indeed, but it has, I would say, pretty major error - if you put solid wall and any insta-breaking block like plants, torches, etc. between yourself and a mob and then hit that plant block, you will probably hit the mob through the blocks.

I found that out when farming nether plants and broke one of nether sprouts block while "aiming" at a horse that was walking below the warped nylium the sprouts were on. That pretty much means, you can hit mobs through any block if you just have specific blocks for that.

![2021-08-01_11 27 23](https://user-images.githubusercontent.com/82406050/127758212-c1fbddf9-1320-46cf-95b1-793458f414bf.png)
![2021-08-01_11 27 32](https://user-images.githubusercontent.com/82406050/127758216-ae8785cc-b59d-4a4c-84d2-4eb1d19c76c5.png)

**Comment by Rongmario** [comment]
Fixed in latest.

**Comment by ohnecksThing** [comment]
Wait, was it fixed only in 1.19? If not, then on Fabric 1.18.2 I can still hit mobs through blocks.

https://user-images.githubusercontent.com/82406050/173199607-f8963338-87c4-426d-a0e5-9d14465bbcd1.mp4
